# Generated by Django 3.2.8 on 2021-12-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211216_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='EntScore',
            field=models.IntegerField(verbose_name=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='ExplorerLocation',
            field=models.IntegerField(verbose_name=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='RestScore',
            field=models.IntegerField(verbose_name=1),
        ),
    ]
