# Generated by Django 3.2.8 on 2021-12-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211216_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='SavedEnt',
            new_name='saved_ent',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='SavedRest',
            new_name='saved_rest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='EntScore',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ExplorerLocation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='RestScore',
        ),
        migrations.AddField(
            model_name='user',
            name='ent_score',
            field=models.IntegerField(default=0, verbose_name=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='explorer_location',
            field=models.IntegerField(default=0, verbose_name=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='rest_score',
            field=models.IntegerField(default=0, verbose_name=int),
            preserve_default=False,
        ),
    ]
