# Generated by Django 3.2.8 on 2022-02-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220218_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ent_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rest_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved_ent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved_rest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_refresh',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_usage',
        ),
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='na', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='na', max_length=100),
            preserve_default=False,
        ),
    ]
