# Generated by Django 3.2.8 on 2022-02-23 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220221_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userName',
        ),
    ]
