# Generated by Django 3.2.8 on 2021-12-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20211216_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ent_score',
            field=models.IntegerField(max_length=int),
        ),
        migrations.AlterField(
            model_name='user',
            name='explorer_location',
            field=models.IntegerField(max_length=int),
        ),
        migrations.AlterField(
            model_name='user',
            name='rest_score',
            field=models.IntegerField(max_length=int),
        ),
    ]
