# Generated by Django 3.2.8 on 2021-12-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20211216_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ent_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='explorer_location',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='rest_score',
            field=models.IntegerField(),
        ),
    ]
