# Generated by Django 3.2.8 on 2021-12-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20211216_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ent_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='explorer_location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rest_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved_ent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved_rest',
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
