# Generated by Django 3.2.8 on 2022-02-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('explorers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorerRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explorerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='explorers.explorer')),
                ('restaurantId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
    ]
