# Generated by Django 3.2.8 on 2021-12-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('explorerentertainments', '0001_initial'),
        ('explorerrestaurants', '0001_initial'),
        ('explorerentratings', '0001_initial'),
        ('explorerrestratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('total_refresh', models.IntegerField()),
                ('total_usage', models.IntegerField()),
                ('location', models.CharField(max_length=250)),
                ('entScore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorerentratings.explorerentrating')),
                ('restScore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorerrestratings.explorerrestrating')),
                ('savedEnt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='explorerentertainments.explorerentertainment')),
                ('savedRest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='explorerrestaurants.explorerrestaurant')),
            ],
        ),
    ]
