# Generated by Django 3.2.8 on 2022-02-26 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explorer',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='explorer',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='explorer',
            old_name='userName',
            new_name='username',
        ),
    ]
