# Generated by Django 3.2.8 on 2022-02-08 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explorer',
            name='entScore',
        ),
        migrations.RemoveField(
            model_name='explorer',
            name='restScore',
        ),
        migrations.RemoveField(
            model_name='explorer',
            name='savedEnt',
        ),
        migrations.RemoveField(
            model_name='explorer',
            name='savedRest',
        ),
    ]
