# Generated by Django 3.2.8 on 2022-02-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorerentratings', '0002_explorerentrating_explorerid'),
        ('explorerentertainments', '0002_explorerentertainment_explorerid'),
        ('explorerrestaurants', '0002_initial'),
        ('explorerrestratings', '0002_initial'),
        ('explorers', '0002_auto_20220208_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explorer',
            name='location',
        ),
        migrations.AddField(
            model_name='explorer',
            name='city',
            field=models.CharField(default='San+Francisco', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='explorer',
            name='entScore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='explorerentratings.explorerentrating'),
        ),
        migrations.AddField(
            model_name='explorer',
            name='restScore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='explorerrestratings.explorerrestrating'),
        ),
        migrations.AddField(
            model_name='explorer',
            name='savedEnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='explorerentertainments.explorerentertainment'),
        ),
        migrations.AddField(
            model_name='explorer',
            name='savedRest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='explorerrestaurants.explorerrestaurant'),
        ),
        migrations.AddField(
            model_name='explorer',
            name='state',
            field=models.CharField(default='CA', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='explorer',
            name='street',
            field=models.CharField(default='39+pier', max_length=50),
            preserve_default=False,
        ),
    ]
