# Generated by Django 3.2.8 on 2022-02-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0003_auto_20220209_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='explorer',
            name='state',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='explorer',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='explorer',
            name='total_refresh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='explorer',
            name='total_usage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
