# Generated by Django 3.2.8 on 2022-02-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0004_auto_20220209_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explorer',
            name='entScore',
        ),
        migrations.RemoveField(
            model_name='explorer',
            name='restScore',
        ),
        migrations.RemoveField(
            model_name='explorer',
            name='savedEnt',
        ),
        migrations.RemoveField(
            model_name='explorer',
            name='savedRest',
        ),
        migrations.RemoveField(
            model_name='explorer',
            name='total_refresh',
        ),
        migrations.RemoveField(
            model_name='explorer',
            name='total_usage',
        ),
        migrations.AddField(
            model_name='explorer',
            name='userName',
            field=models.CharField(default='na', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='explorer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='explorer',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='explorer',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='explorer',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
