# Generated by Django 3.2.8 on 2022-02-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0005_auto_20220221_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explorer',
            name='userName',
        ),
    ]
