# Generated by Django 3.2.8 on 2021-12-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('explorerentertainments', '0001_initial'),
        ('explorers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorerentertainment',
            name='explorerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='explorers.explorer'),
        ),
    ]
